### ISSUE TITLE
Improve `say` Command

### ISSUE THREAD

**Issue by Chr1s70ph** [Chr1s70ph/ETIT-Master#74]
[Say](../blob/master/commands/admin/say.ts) does not yet work with gifs and stickers

**Comment by david-liebscher** [comment]
am besten eine  `!say` command für alle Moderatoren und Admins sowie einen `!edit [NachrichtenID], für Mod und Admins wo man dann genau diese vorher gesendeten nachrichten vom Mod und Admin Team editieren kann, sodass in den faq, Servereinteilung, infos-termine und links alle Moderatoren und Admins die nachrichten ggf. aktualisieren und auf REchtschreibung verbessern können.

**Comment by Chr1s70ph** [comment]
> am besten eine  `!say` command für alle Moderatoren und Admins sowie einen `!edit [NachrichtenID]`, für Mod und Admins wo man dann genau diese vorher gesendeten nachrichten vom Mod und Admin Team editieren kann, sodass in den faq, Servereinteilung, infos-termine und links alle Moderatoren und Admins die nachrichten ggf. aktualisieren und auf REchtschreibung verbessern können.

Die `say` Funktion ist **nicht** dafür ausgelegt, dass sie Moderatoren/Admins Ausführen sollten. Dafür wäre die Implementation von einem anderen Befehlt anstrebender.


---
Also: please keep the comments in english, since the repositories main language is english. If you really need to write in german (or in facz in any other language) please additionally provide a translation.

**Comment by david-liebscher** [comment]
ok Christoph
